[package]
name = "ferrischat_webserver"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
num-traits = "0.2"

ferrischat_db = { path = "../ferrischat_db" }
ferrischat_common = "0.1"

[dependencies.sqlx]
version = "0.4"
features = ["postgres", "macros", "offline", "runtime-actix-rustls"]