on:
  pull_request:

  push:
    branches:
      - main
      - gh-actions-fixes


name: Linters

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: rustup component add rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ferris_chat
          POSTGRES_PASSWORD: ferris_chat
          POSTGRES_PORT: 5432
          POSTGRES_USER: ferris_chat
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: "install ld"
        run: "sudo apt install lld -y"

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: "install sqlx cli"
        run: "cargo install sqlx-cli"

      - name: "run database migrations"
        run: "cargo sqlx migrate run"
        env:
          - DATABASE_URL: "postgres://ferris_chat:ferris_chat@postgres:5432/ferris_chat"

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- --forbid expect_used --forbid unwrap_used
          name: Clippy Output
