on:
  pull_request:

  push:
    branches:
      - main
      - gh-actions-fixes

name: "sqlx checks"

jobs:
  sqlx_check:
    name: "sqlx check"
    runs-on: ubuntu-latest

    services:
      postgres:
        image: "postgres:latest"
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2

      - name: "install rust"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: "install sqlx-cli"
        run: "cargo install sqlx-cli"

      - name: "save current sqlx-data.json"
        run: "mv sqlx-data.json sqlx-data.json.old || touch sqlx-data.json.old"

      - name: "migrate db"
        run: "cargo sqlx database setup"
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/ferris_chat"

      - name: "regenerate sqlx-data.json"
        run: "cargo sqlx prepare"
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/ferris_chat"

      - name: "assert eq"
        run: "diff -q sqlx-data.json sqlx-data.json.old"
